---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-engine-steam
  namespace: classification
  labels:
    helm.sh/chart: some-chart
    app.kubernetes.io/name: flux-engine-steam
    app: flux-engine-steam
    app.kubernetes.io/version: 0.0.27-pre1
    app.kubernetes.io/managed-by: releaser
  annotations:
    github.com/repository_url: git@github.com:flux-engine-steam
    color: blue
spec:
  replicas: 4
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: flux-engine-steam
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: app
        github.com/repository_url: git@github.com:flux-engine-steam
        color: blue
      labels:
        helm.sh/chart: flux-engine-steam-2.28.12
        app.kubernetes.io/name: flux-engine-steam
        app: flux-engine-steam
        app.kubernetes.io/version: 0.0.27-pre1
        app.kubernetes.io/managed-by: releaser
    spec:
      imagePullSecrets:
      - name: aws-registry
      - name: docker-registry
      serviceAccountName: default
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: flux-engine-steam
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: flux-engine-steam
      terminationGracePeriodSeconds: 30
      containers:
      - name: app
        image: flux-engine-steam:v0.0.27-pre1
        ports:
        - name: https
          containerPort: 8501
        env:
        - name: COLOR
          value: "blue"
        - name: K8S_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVICE_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: k8s.host.ip=$(K8S_HOST_IP),k8s.namespace.name=$(K8S_POD_NAMESPACE),k8s.pod.ip=$(K8S_POD_IP),k8s.pod.name=$(K8S_POD_NAME),service.version=$(SERVICE_VERSION)
        - name: OTEL_SEMCONV_STABILITY_OPT_IN
          value: http/dup
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8501
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 1
            ephemeral-storage: 2Gi
            memory: 1.5Gi
          requests:
            cpu: '0.2'
            ephemeral-storage: 1.2Gi
            memory: 100Mi
      dnsConfig:
        options:
        - name: ndots
          value: '2'
        - name: single-request-reopen
---
apiVersion: v1
kind: Service
metadata:
  name: flux-engine-steam
  namespace: classification
  labels:
    helm.sh/chart: flux-engine-steam-2.28.12
    app.kubernetes.io/name: flux-engine-steam
    app: flux-engine-steam
    app.kubernetes.io/version: 0.0.27-pre1
    app.kubernetes.io/managed-by: batman
spec:
  ports:
  - targetPort: 8502
    port: 3000
    name: https
  selector:
    app: flux-engine-steam
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flux-engine-steam
  namespace: classification
  labels:
    helm.sh/chart: flux-engine-steam-2.28.12
    app.kubernetes.io/name: flux-engine-steam
    app: flux-engine-steam
    app.kubernetes.io/managed-by: batman
  annotations:
    github.com/repository_url: git@github.com:flux-engine-steam
spec:
  podSelector:
    matchLabels:
      app: flux-engine-steam
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: opentelemetry-operator-system
    ports:
    - port: 14268
    - port: 4317
    - port: 4318
    - port: 9411
    - port: 13133
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
      - port: 53
  ingress: []
